### ISSUE TITLE
appendLine/appendString block names swapped

### ISSUE THREAD

**Issue by simonmorrish** [Microsoft/pxt-filesystem#4] opened 2017-01-28 18:08 UTC
The block comments for appendLine and appendString are incorrect, leading to the two functions being named the wrong way round in the PXT blocks editor:

files.cpp, L31 is:
   `//% blockId="files_append_line" block="file %filename|append string %text"`
should be:
  `//% blockId="files_append_line" block="file %filename|append line %text"`

files.cpp, L48 is:
   `//% blockId="fs_append_string" block="file %filename|append line %text"`
should be:
   `//% blockId="fs_append_string" block="file %filename|append string %text"`

I have submitted a change.

**Comment by pelikhan** [comment] 2017-03-07 17:29
Thank for reporting this. The issue is fixed in 0.3.1.

**Closed as completed by pelikhan** 2017-03-07 17:29 UTC
